image: eu.gcr.io/movici-develop/cicd-pipeline-tools:latest

stages:
  - verify
  - test
  - build
  - upload

variables:
  KUBERNETES_MEMORY_REQUEST: 1536Mi
  KUBERNETES_MEMORY_LIMIT: 1536Mi
  KUBERNETES_CPU_REQUEST: 600m
  KUBERNETES_CPU_LIMIT: 1000m

check_version_upgrade:
  stage: verify
  image: alpine/git
  only:
    refs:
      - merge_requests
  variables:
    VERSION_FILES: "VERSION"
  script:
    - git fetch origin master
    - |-
      if [[ -z $(git diff origin/master --name-only ${VERSION_FILES}) ]]; then
        echo "All merge requests require a version upgrade. Please update your version"
        exit 1
      fi
.test:
  image: eu.gcr.io/movici-develop/cicd-build-tools:latest
  stage: test
  only:
    refs:
      - merge_requests
      - master
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install .
    - make test-all
test:3.8:
  extends: .test
  image: eu.gcr.io/movici-develop/cicd-build-tools:python3.8

test:3.9:
  extends: .test
  image: eu.gcr.io/movici-develop/cicd-build-tools:python3.9

test:3.10:
  extends: .test
  image: eu.gcr.io/movici-develop/cicd-build-tools:python3.10

.build:
  stage: build
  only:
    refs:
      - merge_requests
      - master
  artifacts:
    untracked: true
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip wheel --no-deps .

build:3.8:
  extends: .build
  image: eu.gcr.io/movici-develop/cicd-build-tools:python3.8

build:3.9:
  extends: .build
  image: eu.gcr.io/movici-develop/cicd-build-tools:python3.9

build:3.10:
  extends: .build
  image: eu.gcr.io/movici-develop/cicd-build-tools:python3.10

upload:
  stage: upload
  dependencies:
    - build:3.8
    - build:3.9
    - build:3.10
  only:
    - master
    - /^.*testci-.*$/
  script:
    - twine upload --repository-url $PYPI_SERVER *.whl