image: eu.gcr.io/movici-develop/cicd-pipeline-tools:latest

stages:
  - test
  - build
  - upload

variables:
  KUBERNETES_MEMORY_REQUEST: 1536Mi
  KUBERNETES_MEMORY_LIMIT: 1536Mi
  KUBERNETES_CPU_REQUEST: 600m
  KUBERNETES_CPU_LIMIT: 1000m

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install .
    - make test-all

build:
  image: eu.gcr.io/movici-develop/cicd-build-tools:latest
  stage: build
  artifacts:
    untracked: true
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip wheel --no-deps .

upload:
  stage: upload
  dependencies:
    - build
  only:
    - master
    - /^.*testci-.*$/
  script:
    - twine upload --repository-url $PYPI_SERVER *.whl