name: "Install Boost Headers"

inputs:
  os:
    description: "The currently running os"
    required: true
  boost-dir:
    description: "The directory to install boost headers"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install boost (Windows)
      if: inputs.os == 'windows-latest'
      shell: pwsh
      env:
        BOOST_DIR: ${{ inputs.boost-dir }}
      run: |
        $Env:BOOST_VERSION_DOT = $Env:BOOST_VERSION -replace '_','.'

        Invoke-WebRequest -Uri "https://archives.boost.io/release/$Env:BOOST_VERSION_DOT/source/boost_$Env:BOOST_VERSION.zip" -OutFile "boost.zip"

        Expand-Archive -Path "boost.zip" -DestinationPath .
        mkdir -p $Env:BOOST_DIR
        Move-Item "boost_$Env:BOOST_VERSION/boost/*" $Env:BOOST_DIR

    - name: Install boost (Linux)
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      env:
        BOOST_DIR: ${{ inputs.boost-dir }}
      run: |
        BOOST_VERSION_DOT=$(echo ${BOOST_VERSION} | sed s/_/./g)

        wget -q https://archives.boost.io/release/${BOOST_VERSION_DOT}/source/boost_${BOOST_VERSION}.tar.gz -O boost.tar.gz

        tar -xzf boost.tar.gz
        mkdir -p ${BOOST_DIR}
        mv boost_${BOOST_VERSION}/boost/* ${BOOST_DIR}
