name: Build and Deploy

# on:
#   workflow_run:
#     workflows: ["Main"]
#     types: 
#       - completed

env:
  BOOST_DIR: "boost/boost"
  BOOST_VERSION: 1_79_0

jobs:
  build:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            sdist: "gztar"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Boost
        uses: ./.github/actions/install-boost
        with:
          os: ${{ matrix.os }}
          boost-dir: ${{ env.BOOST_DIR }}

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Build source distribution
        if: ${{ matrix.sdist }}
        env:
          SDIST_FORMAT: ${{ matrix.sdist }}
        run: |
          python setup.py sdist --formats ${SDIST_FORMAT} --dist-dir dist/

      - name: Build wheel
        if: "! ${{ matrix.sdist }}"
        run: |
          pip wheel --no-deps --wheel-dir dist/ .

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: 'distributions'
  deploy:
    runs-on: "ubuntu-latest"
    needs: ['build']
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: distributions
          path: dist/
      
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      