name: Build and Deploy

on:
  pull_request:
  workflow_run:
    workflows: ["Main"]
    branches:
      - master
      - main
    types: 
      - completed

env:
  BOOST_DIR: "boost/boost"
  BOOST_VERSION: 1_79_0

jobs:
  build-wheels:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "cp38-manylinux_x86_64"
          - os: ubuntu-latest
            python-version: "cp39-manylinux_x86_64"
          - os: ubuntu-latest
            python-version: "cp310-manylinux_x86_64"
          - os: windows-latest
            python-version: "cp38-win_amd64"
          - os: windows-latest
            python-version: "cp39-win_amd64"
          - os: windows-latest
            python-version: "cp310-win_amd64"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Boost
        uses: ./.github/actions/install-boost
        with:
          os: ${{ matrix.os }}
          boost-dir: ${{ env.BOOST_DIR }}
      
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.0
        env:
          CIBW_BUILD: ${{ matrix.python-version }}
          CIBW_ENVIRONMENT: BOOST_DIR=${{ env.BOOST_DIR }}
          CIBW_TEST_COMMAND: pytest {project}/tests/python
        with:
          output-dir: dist/

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: 'distributions'
  build-sdist:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          pip install pybind11

      - name: Build source distribution
        run: |
          python setup.py sdist --formats gztar --dist-dir dist/

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: distributions

  deploy:
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: distributions
          path: dist/
      
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      