name: Linting

on:
  pull_request:
    types: [synchronize]
  push:
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Build and install
        run: |
          pip install black

      - name: Run black
        run: |
          black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Build and install
        run: |
          pip install flake8

      - name: Run Flake8
        run: |
          make flake8