name: Testing (Python)

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.10"

    runs-on: ${{ matrix.os }}
    env:
      BOOST_DIR: "boost/boost"
      BOOST_VERSION: 1_79_0

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install boost (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $Env:BOOST_VERSION_DOT = $Env:BOOST_VERSION -replace '_','.'

          Invoke-WebRequest -Uri "https://boostorg.jfrog.io/artifactory/main/release/$Env:BOOST_VERSION_DOT/source/boost_$Env:BOOST_VERSION.tar.gz" -OutFile "boost.tar.gz"

          tar -xzf boost.tar.gz
          mv "boost_$Env:BOOST_VERSION/boost" boost/

      - name: Install boost (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          BOOST_VERSION_DOT=$(echo ${BOOST_VERSION} | sed s/_/./g)

          wget -q https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION_DOT}/source/boost_${BOOST_VERSION}.tar.gz -O boost.tar.gz

          tar -xzf boost.tar.gz
          mv boost_${BOOST_VERSION}/boost boost/

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Build and install
        run: |
          pip install .

      - name: Test with pytest
        run: |
          pytest tests/python
